# Generated by Django 4.0.3 on 2022-03-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_title_userdepartment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
